# 增加hello接口测试test.http

GET http://localhost:8082/hello
#Accept: application/json

##结果验证

> {%
client.test("test-hello", function() {
  client.log("测试/hello接口");
  client.log(response.body);
  client.log(JSON.stringify(response.body)); // 虽然idea没有提示JSON，但是可以用
  client.assert(response.status === 200, "返回码不是200");
  client.assert(response.body === "Hello World", "结果验证失败");
});
%}

###

POST http://localhost:8082/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST


###


GET http://localhost:8082/test/list

###

GET http://localhost:8083/test/redis/set/123/test
Accept: application/json

###

GET http://localhost:8083/redis/get/59172457675886592
Accept: application/json

###
