###
GET http://localhost:8083/user/list


###
GET http://localhost:8083/user/list?userName=admin

###
GET http://localhost:8083/user/list?userName=admin2


###
POST http://localhost:8083/user/save
Content-Type: application/json

{
  "userName": "admin4",
  "name": "张志成",
  "password": "46f94c8de14fb36680850768ff1b7f2a",
  "email": "2512466133@qq.com",
  "telNum": "19912341234"
}

###
DELETE http://localhost:8083/user/delete/3


###
POST http://localhost:8083/user/reset-password
Content-Type: application/json

{
  "uid": "admin3",
  "password": "321asd"
}


###
POST http://localhost:8083/user/login
Content-Type: application/json

{
  "userName": "admin4",
  "password": "200820e3227815ed1756a6b531e7e0d2"
}